bandb/main/models.py
'''
Created on May 3, 2017

@author: wjgallag
'''

bandb/main/forms.py
'''
Created on May 3, 2017

@author: wjgallag
'''
try:
    from flask_wtf import FlaskForm
except ImportError:
    from flask_wtf import Form as FlaskForm
from wtforms import StringField, SubmitField
from wtforms.fields.html5 import EmailField
from wtforms.validators import InputRequired, Email

class EmailForm(FlaskForm):
    name = StringField(validators=[InputRequired()])
    email = EmailField(validators=[InputRequired(), Email()])
    submit = SubmitField('Submit')

bandb/main/__init__.py

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

bandb/main/views.py

from flask import render_template, request, flash

from . import main
from .forms import EmailForm

def is_dev_mode():
    return request.args.get('dev') is not None

@main.route('/', methods=['GET', 'POST'])
def index():
    form = EmailForm()
    errors = None
    if (form.validate_on_submit()):
        with open('emails.txt', 'a+') as f:
            f.write(form.name.data + ',' + form.email.data + '\n')
        form = None
    elif (form.errors):
        #flash(form.errors)
        errors = form.errors
    return render_template('main/index.html', dev=is_dev_mode(), form=form, errors=errors)

@main.route('/hotel')
def hotel():
    return render_template('main/hotel.html', dev=is_dev_mode())

bandb/templates/main/panels/events.html
<div class="background">
	<div class="section events">
		<div class="container">
			<div class="row no-gaps">
				<h1 class="col">The Itinerary</h1>
			</div>
			<div class="row">
				<h3 class="col typewriter">12 April 2018</h3>
			</div>
			<div class="row">
				<div class="col xs-full m-half xl-third">
					<img src="/static/img/main/index/nats.png">
				</div>
				<div class="col xs-full m-half xl-third">
					<div class="row as-col no-gutter align-center">
						<h5 class="col typewriter">7:05pm</h5>
						<h5 class="col typewriter">Nats vs Rockies</h5>
						<div class="col">Watch the Washington Nationals take on the
							Colorado Rockies just a few blocks from the Navy Yard</div>
						<h5 class="col">National's Park</h5>
						<div class="col">1500 S Capitol St SE<br>Washington, DC 20003<br>
							Use Navy Yard Metro station on the Green line<br>
							<a href="https://goo.gl/maps/6zuHLm9uwLs" target="_blank">Map</a></div>
						<div class="col">Meet at the corner of 1st and N at 6:50 PM</div>
					</div>
				</div>
			</div>
			<div class="row">
				<h3 class="col typewriter">13 April 2018</h3>
			</div>
			<div class="row">
				<div class="col xs-full m-half xl-third">
					<div class="row as-col no-gutter align-center">
						<h5 class="col typewriter">6:30pm</h5>
						<h5 class="col typewriter">5K Friday</h5>
						<div class="col">Run a fun 5K for charity through Crystal City,
							just across the Potomac River from DC</div>
						<h5 class="col">Crystal City, VA</h5>
						<div class="col">Crystal Dr<br>Arlington, VA 22202<br>
							Use Crystal City Metro station on the Blue/Yellow lines<br>
							<a href="https://goo.gl/maps/HvDpJpXkqXx" target="_blank">Map</a></div>
						<div class="col">Meet at 2100 Crystal Dr in front of Capital One at 6:00 PM</div>
					</div>
				</div>
				<div class="col xs-full m-half xl-third">
					<img src="/static/img/main/index/5k.jpg">
				</div>
			</div>
			<div class="row">
				<h3 class="col typewriter">14 April 2018</h3>
			</div>
			<div class="row">
				<div class="col xs-full m-half xl-third">
					<img src="/static/img/main/index/easternmarket.png">
				</div>
				<div class="col xs-full m-half xl-third">
					<div class="row as-col no-gutter align-center">
						<h5 class="col typewriter">6:00pm</h5>
						<h5 class="col typewriter">Ceremony</h5>
						<div class="col">Join us as we take of on our next adventure</div>
						<h5 class="col typewriter">Happy Hour</h5>
						<div class="col">Enjoy the scenery with drinks and snacks</div>
						<h5 class="col typewriter">Reception</h5>
						<div class="col">Dinner and dancing into the night</div>
						<h5 class="col">Eastern Market</h5>
						<div class="col">215 7th St SE<br>Washington, DC 20003<br>
							Use Eastern Market Metro station on the Blue/Orange/Silver lines<br>
							<a href="https://goo.gl/maps/UbknCY1zcFk" target="_blank">Map</a></div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col xs-full m-three-quarters xl-two-thirds">
					<div class="row as-col no-gutter align-center">
						<div class="col">Shuttle service will be provided from the Capitol Hill Hotel starting at 5:45 PM</div>
						<div class="col">Free street parking is available in the neighborhood north of North Carolina Ave, but note that 7th St by Eastern Market will be closed to vehicles.</div>
						<div class="col">Enter through the door at the north end on North Carolina Ave</div>
						<div class="col">Cocktail attire is requested</div>
					</div>
				</div>
			</div>
			<div class="row">
				<h3 class="col typewriter">15 April 2018</h3>
			</div>
			<div class="row">
				<div class="col">
					<div class="row as-col no-gutter align-center">
						<h5 class="col typewriter">10:00am - 2:00pm</h5>
						<h5 class="col typewriter">Brunch</h5>
						<div class="col">Stop by our home in Capitol Hill for a casual brunch.</div>
						<div class="col">Come when you can, stay as long as you like!</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/hotelcontact.html
<div class="background">
	<div class="section contact">
		<div class="container">
			<div class="row">
				<h3 class="col">To Make Reservations</h3>
			</div>
			<div class="row">
				<div class="col">
					<div class="row as-col">
						<div class="col">
							Visit <a href="http://bitly.com/BsquaredDC" target="_blank">http://bitlycom/BsquaredDC</a>
						</div>
						<div class="col">OR</div>
						<div class="col">
							Call <a href="tel:+12024482081">202-448-2081</a> and request the<br>
							"Gallagher/Congdon Wedding"
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<div class="row as-col">
						<div class="col problems">
							If you encounter any problems booking, you may call Patti Gallagher
							at <a href="tel:+18004460518">800-446-0518</a> for assistance.
						</div>
						<div class="col instructions">
							When reserving online, be sure to choose "Search Dates", then select
							a check-in date, checkout-out date, and click "Check Availability".
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/hoteldetails.html
<div class="background">
	<div class="section details">
		<div class="container">
			<div class="row">
				<h3 class="col">About the Capitol Hill Hotel</h3>
			</div>
			<div class="row">
				<div class="col xs-full m-three-quarters xl-half align-justify">
					Discover the tranquil beauty of the Capitol Hill Historic
					District in one of the most centrally located hotels in
					Washington, DC. Elegant and intimate, Capitol Hill
					Hotel is a home away from home in the heart of the
					nation’s capital, tucked away amidst the charming
					brick rowhouses of a residential neighborhood yet just
					a short walk away from Washington’s most important
					sites, including the Capitol Building, Supreme Court,
					Library of Congress, and the National Mall.
				</div>
			</div>
			<div class="row">
				<div class="col align-center">
					200 C St SE<br>Washington, DC 20003<br>
					<a href="https://goo.gl/maps/UixgfaXL7Nq" target="_blank">Map</a>
				</div>
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/hotelintro.html
<div class="background">
	<div class="section intro">
		<div class="container">
			<div class="row">
				<h2 class="col">Capitol Hill Hotel</h2>
			</div>
			<div class="row">
				<div class="col xs-full m-half xl-third">
					<img src="/static/img/main/hotel/hotel.jpg">
				</div>
				<div class="col xs-full m-half xl-third">
					<div class="row as-col no-gutter align-center">
						<h5 class="col">Welcome to Our Neighborhood</h5>
						<div class="col align-justify">
							We want everybody to be able to experience our
							neighborhood and enjoy their time in DC. We have
							reserved a block of rooms at the Capitol Hill Hotel for
							the nights of April 12, 13, & 14, 2018. The hotel is just a
							10 minute walk to the wedding at Eastern Market, and
							we’ll also provide transportation from the hotel.
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/intro.html
<div class="background">
	<div class="section intro">
		<div class="container">
			<div class="row">
				<div class="col xs-full m-four-fifths xl-three-quarters">
					<div>
						<h1>We're Thrilled!</h1>
						<p>As two people who love adventures, we are both so excited to begin our journey, 
						and to have our friends and family join us for this celebration.  Each and every one
						of you is special to us, and we hope that you're just as eager as we are to cherish
						old memories and make new ones!  On this website, we've endeavored to provide all the 
						information you need to join us, and we hope that you'll use it to share your thoughts, 
						ideas, and pictures with us.</p>
						<p>Thanks, and see you soon!</p>
						<div class="signature">Billy &amp; Betsy</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/lodging.html
<div class="background">
	<div class="section events">
		<div class="container">
			<div class="row no-gaps">
				<h2 class="col">Accomodations</h2>
			</div>
			<div class="row">
				<div class="col xs-full m-half xl-third">
					<img src="/static/img/main/index/hotel.png">
				</div>
				<div class="col xs-full m-half xl-third">
					<div class="row as-col no-gutter align-center">
						<h5 class="col typewriter">The Capitol Hill Hotel</h5>
						<div class="col">Rooms are available at a special rate at this nearby hotel just for our guests</div>
						<div class="col">200 C St SE<br>Washington, DC 20003</div>
						<div class="col"><a href="{{ url_for('main.hotel') }}">Details and Reservations</a></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/map.html
<div class="background">
	<div class="section events">
		<div class="container">
			<div class="row">
				<div class="col">
					<object type="image/svg+xml" data="/static/img/main/index/map_vert.svg" class="map l-hidden"></object>
					<object type="image/svg+xml" data="/static/img/main/index/map_horiz.svg" class="map hidden l-visible"></object>
				</div>
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/more.html
<div class="background">
	<div class="section more">
		<div class="container">
			<a name="more"></a>
			<div class="row">
				<h2 class="col">
                    Don't worry, we'll answer all your questions as the details are finalized! Check back soon for more!  If you want us to let you know, fill in your information below!
                </h2>
			</div>
			{% if form %}
				<form action="{{ url_for('main.index') }}#more" method="post">
				{{ form.hidden_tag() }}
					<div class="row">
						<div class="col input-field">
							{% if errors.name %}
								{{ form.name(class_="validate invalid", required="required") }}
							{% else %}
								{{ form.name(class_="validate", required="required") }}
							{% endif %}
							<label for="{{ form.name.id }}">Name</label>
						</div>
						<div class="col input-field">
							{% if errors.email %}
								{{ form.email(class_="validate invalid", required="required") }}
							{% else %}
								{{ form.email(class_="validate", required="required") }}
							{% endif %}
							<label for="{{ form.email.id }}" data-error="Please enter a valid email">Email</label>
						</div>
						<div class="col input-field">
							<button class="btn" type="submit" name="action">Submit</button>
						</div>
					</div>
				</form>
			{% else %}
				<h4 class="col">
                    Thanks, we'll let you know when we update this page!
                </h4>
			{% endif %}
		</div>
	</div>
</div>

bandb/templates/main/panels/party.html
{# from 'main/panels/person.html' import person #}

{% macro person(name, side, image) %}
	<div class="col person xs-full m-half xl-third">
		<img src="../static/img/main/index/{{ image }}.jpg" />
		<h4 class="name">{{name}}</h4>
		<h6>{{side}}'s Side</h6>
		{{ caller() }}
	</div>
{% endmacro %}

<div class="background">
	<div class="section party">
		<div class="container">
			<div class="row no-gaps">
				<h1 class="col">The Flight Crew</h1>
			</div>
			<div class="row ">
				<h5 class="col">(Yes, there are 3 Jen's in the wedding party!)</h5>
			</div>
			<div class="row"><div class="col"></div></div>
			<div class="row items-space-around">
				{% call person('Tanner', 'Billy', 'tanner') %}
					<p>Tanner and I lived across the hall from each other freshman year at Notre Dame. We quickly became great friends,
						and were roommates the following three years. We've got many great stories, and he is ever asking for a pony!
						Now he's a doctor in Pittsburgh finding a cure for cancer (and a way to build a spaceship out of proteins).
					</p>
				{% endcall %}
				{% call person('David', 'Betsy', 'david') %}
					<p>
							It's kind of complicated, but we met in college and have been great friends ever since! It is hard to believe that we have known each other for almost 14 years now. David and Patrick live not far from us in DC. He is an expert in event planning of all kinds: classy parties, receiving lines, and ridiculous Halloween Parties. And If you ever run a half marathon, he'll be happy to feed you amazing food after you finish!
					</p>
				{% endcall %}
				{% call person('Deny', 'Billy', 'deny') %}
					<p>
						My younger brother and I have always been very close! We've shared our love of many things, like soccer and 
						Seinfield, and he's taught me how to be more outgoing! He also spent four years in the midwest, at Marquette 
						Univeristy in Milwaukee, and now works in New York City making awesome radio programs and podcasts.
					</p>
				{% endcall %}
				{% call person('Jen G', 'Betsy', 'jeng') %}
					<p>
							We met originally through Patrick, and spent the last decade living it up in DC. Jen is now our neighbor, just a block away from us, which is perfect for grabbing dinner or enjoying Nutella bombs from The Pretzel Bakery together. Jen and I also love going to Caps and Nats games together. Jen is also an avid soccer fan, both of the US National teams and the DC United.
					</p>
				{% endcall %}
				{% call person('Jen H', 'Billy', 'jenh') %}
					<p>
						She may deny it, but Jen is from North Jersey! We met before freshman year at a send off dinner for new Notre 
						Dame students and bonded over marching band. After college, Jen was always happy to answer the phone and provide
						plenty of advice! Jen works in pediatrics, living in North Carolina with her husband and adorable little daughter.
					</p>
				{% endcall %}
				{% call person('Patrick', 'Betsy', 'patrick') %}
					<p>
							We met through David and became fast friends. Since David and Patrick are so close to us in DC, we always are up for dinner or drinks out. Patrick has an amazing sense of humor and excels in improv comedy. He can always be counted on for a good laugh!
					</p>
				{% endcall %}
				{% call person('Jenn T', 'Billy', 'jenn') %}
					<p>
						A fellow PhD student at Georgia Tech, Jenn was always up for grabbing a drink and complaining about grad school!
						She's originally from New Jersery, is an excellent pilot who flies helicopters and vintage warbirds, and will 
						eagerly show you cool features of rock formations, especially from volcanos! She and Shahin live in Atlanta.
					</p>
				{% endcall %}
				{% call person('Simmie', 'Betsy', 'simmie') %}
					<p>
							We originally met at APL building spacecraft, and then became roommates when I lived out in the suburbs. Simmie loves to bake: delicious cakes, cookies, and hamentashen. Simmie has many hidden talents and hobbies including Tae Kwon Do, Roller Derby and running races. Ask Simmie about her chocolate chip cookie recipe, they are my favorite!
					</p>
				{% endcall %}
				{% call person('Shahin', 'Billy', 'shahin') %}
					<p>
						Shahin was one of the first people I met when I joined the Yellow Jacket Flying Club at Georgia Tech. We've had lots of
						great flying adventures, including a couple trips to EAA AirVenture Oshkosh. Though video replay showed he had a head
						start at the YJFC Air Rally... After previously working at JSC, he now works for Delta, and he and Jenn live in Atlanta.
					</p>
				{% endcall %}
				{% call person('Shelby', 'Betsy', 'shelby') %}
					<p>
							Shelby was my roommate freshman year at Stanford and we have been friends for over 13 years.  We weathered the Toyon plague and Marguerite rides to Target together. Shelby is a lover of languages and all things biology. After spending some time in Central America and South Korea as a teacher, Shelby is now teaching in New York City, where she and her husband live.
					</p>
				{% endcall %}
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/registry.html
<div class="background">
    <div class="section registry">
        <div class="container">
            <div class="row no-gaps">
                <h1 class="col">The Travel Supplies</h1>
            </div>
            <!-- <div class="row">
                <h4 class="col m-three-quarters xl-three-fifths">We're delighted to know that you'll be there to share the excitement,
                    and that's all we need! But if you must know, there's are a few things we could use for our journey!  We'll let you
                    know soon when we've finished making our packing list.</h4>
            </div> -->
            <div class="row">
                <h4 class="col m-three-quarters xl-three-fifths">We're delighted to know that you'll be there to share the excitement,
                    and that's all we need! But if you must know, here's a few things we could use for our journey!</h4>
            </div>
            <div class="row">
                <a href="https://bit.ly/2AlHGZf" target="_blank" class="col row as-col wrap-none">
                    <h5 class="col">REI - Supplies for the outdoors</h5>
                    <div class="col valign-middle"><img src="/static/img/main/index/rei_light.png"></div>
                </a>
                <a href="https://crate.us/2ASIzJX" target="_blank" class="col row as-col wrap-none">
                    <h5 class="col">Crate and Barrel - Supplies for the home &amp; kitchen</h5>
                    <div class="col valign-middle"><img src="/static/img/main/index/crateandbarrel_light.png"></div>
                </a>
                <a href="https://bit.ly/2jaJBbV" target="_new" class="col row as-col wrap-none">
                    <h5 class="col">Williams Sonoa - Supplies for the home &amp; kitchen</h5>
                    <div class="col valign-middle"><img src="/static/img/main/index/williamssonoma_light.png"></div>
                </a>
                <a href="https://amzn.to/2C24Vbk" target="_new" class="col row as-col wrap-none">
                    <h5 class="col">Amazon - Supplies for everything in between</h5>
                    <div class="col valign-middle"><img src="/static/img/main/index/amazon_light.png"></div>
                </a>
            </div>
        </div>
    </div>
</div>

bandb/templates/main/panels/story.html
<div class="background">
	<div class="section story">
		<div class="container">
			<div class="row no-gaps">
				<h1 class="col">The Travel Log</h1>
			</div>
			<div class="row">
				<div class="col chapter">
					<img src="/static/img/main/index/meeting.jpg">
					<h3 class="elegant">We Met Staring at the Moon</h3>
					<p>One spring spring night back in 2014 (April 8th, to be specific), Katelyn, a mutual friend that Billy knew from his time at JPL and Betsy
						knew from a project at work at APL, invited both of us to an open observatory night at the Smithsonian National Air and Space Museum.
						Everybody else was late, but we were both on time!  So we found each other and got in line to look through the telescope.  Half an hour
						later, amidst finding out just how many common interests we have, we got to the front of the line and gazed at the Moon through the 
						telescope.</p>
					<p>The rest of the night, we look at stars and planets, and talked about traveling, rock climbing, college football, and more.  Billy gave 
						Betsy a ride home at the end of the night, and a few days later (April 13th), we had our first date at Jaleo in downtown DC.  We spent 
						hours enjoying the sangria, talking about all manner of things, including the places we wanted to go!  After dinner, we stopped for gelato 
						at Pitango, then went for a stroll on the National Mall under the light of the nearly full Moon.  We met looking at the Moon, and ever since,
						we can look up at the Moon and, no matter where we are, think of each other!</p>
				</div>
			</div>
			<div class="row">
				<div class="col chapter">
					<img src="/static/img/main/index/engagement.jpg">
					<h3 class="elegant">We Were Engaged Under the Stars</h3>
					<p>On the night of the full Moon and a partial lunar eclipse in February of 2017, we went down to the National Mall, outside the Air and Space
						Museum, ostensibly for Billy to take pictures of the eclipse.  The chilly, cloudy weather conspired to hide the Moon from view, but that 
						didn't stand in the way!  After setting up his camera, Billy pulled out the ring and proposed, and Betsy, of course, said yes!  While Betsy 
						suspected something might be up, what she didn't know was that Billy had assembled family and friends to meet us there!</p>
					<p>After the proposal, we, along with our families, went to the National Arboretum for a guided walk through the gardens and groves under the
						full Moon.  About halfway through, the clouds cleared and the moon came out!  We then met up with friends who came from all over the country
						at Harold Black, a speakeasy style bar across the street from Eastern Market to enjoy drinks!</p>
				</div>
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/summary.html
<div class="background">
	<div class="section save-the-date">
		<div class="container">
			<div class="row">
				<div class="col front">
					<div>Fly me to the Moon</div>
				</div>
				<div class="col back">
					<div class="row as-col no-gutter no-gaps">
						<div class="col"><div class="field">Itinerary:</div></div>
						<div class="col"><div class="value">Billy and Betsy's Wedding</div></div>
						<div class="col"><div class="field">Destination:</div></div>
						<div class="col"><div class="value">Washington, DC</div></div>
						<div class="col"><div class="field">Date of Travel:</div></div>
						<div class="col"><div class="value">14 April 2018</div></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/transportation.html
<div class="background">
	<div class="section events">
		<div class="container">
			<div class="row no-gaps">
				<h2 class="col">Transportation</h2>
			</div>
			<div class="row">
				<div class="col xs-full m-half">
					<div class="row as-col no-gutter align-center">
						<div class="col">Shuttles will be provided from the hotel to venue</div>
						<div class="col"><img src="/static/img/main/easternmarket.png"></div>
					</div>
				</div>
				<div class="col xs-full m-half">
					<div class="row as-col no-gutter align-center">
						<div class="col">Both the hotel and venue are easily accessible by Metro</div>
						<div class="col"><img src="/static/img/main/easternmarket.png"></div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col xs-full m-half">
					<div class="row as-col no-gutter align-center">
						<div class="col">Ronald Reagan National Airport (DCA) is only 15 minutes from Capitol Hill</div>
						<div class="col">Dulles International Airport (IAD) and Baltimore-Washington International Airport (BWI) are also nearby</div>
						<div class="col"><img src="/static/img/main/easternmarket.png"></div>
					</div>
				</div>
				<div class="col xs-full m-half">
					<div class="row as-col no-gutter align-center">
						<div class="col">Union Station is nearby for those arriving by Amtrak, MARC, or VRE trains</div>
						<div class="col"><img src="/static/img/main/easternmarket.png"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

bandb/templates/main/panels/us.html
<div class="background">
	<div class="section us">
		<div class="container">
			<div class="row no-gaps">
				<h1 class="col">The Adventurers</h1>
			</div>
			<div class="row">
				<div class="col person">
					<img src="/static/img/main/index/billy.jpg">
					<h3 class="name">Billy Gallagher</h3>
					<p>I love to travel and I love space!  I also love building things, and always have a project or two (ok, maybe three...) going on.  Oh, and I have my pilot's license!  I
						grew up in North Jersey, spent 4 years in Northern Indiana at Notre Dame, eight years in Atlanta at Georgia Tech, and even part of a year in Southern California at JPL
						before finding my way to Washington, DC, where I work for NASA building space robots.  Each of these places and the people I met there are part of who I am today!</p>
					<p>I knew pretty early on that Betsy was special!  When we went to the Air and Space Museum, and afterwards she said she was so happy I was willing to come along, when I 
						assumed I was the one making her tag along, it was pretty clear!  I know that together, the next adventure is always just around the corner, whether it's an exciting 
						trip to an exotic place or just an evening walk to dinner down the street, and that it will be an amazing journey!</p>
				</div>
				<div class="col person">
					<img src="/static/img/main/index/betsy2.jpg">
					<h3 class="name">Betsy Congdon</h3>
					<p>I am a spacecraft building, West Wing loving, runner who has been living in the DC area for almost ten years.  While my family hails from Northern Indiana, I have lived 
						in Atlanta, Dallas, New Jersey, and Northern California.  Unsurprisingly, I spend a lot of time traveling in my free time, and enjoy visiting new places and seeing new
						things.  I also love going to Nats, Caps, and Stanford football games and Billy has gotten me more into soccer.  
					<p>Billy and I clicked pretty quickly, and we started spending almost all of our time together soon after we first met.  Whether it was a trying a new restaurant, drinking 
						new beers at local breweries, rock climbing, going to a concert, or doing the crossword together each night, it was clear we were a great match.  I'm looking forward
						to good times and new experiences in the future!
				</div>
			</div>
		</div>
	</div>
</div>