bandb/rsvp/forms.py
'''
Created on May 3, 2017

@author: wjgallag
'''

try:
    from flask_wtf import FlaskForm
except ImportError:
    from flask_wtf import Form as FlaskForm
from wtforms import StringField, SubmitField, SelectMultipleField, RadioField, FieldList
from wtforms.fields.html5 import EmailField
from wtforms.validators import InputRequired, Length, Email
from wtforms.widgets import TableWidget, CheckboxInput

class VerifyForm(FlaskForm):
    last_name = StringField(validators=[InputRequired()])
    invite_code = StringField(validators=[InputRequired(), Length(min=4,max=4)])
    submit = SubmitField('Submit')

class ResponseForm(FlaskForm):
    attending = RadioField(choices=[(1, 'Love to!'), (0, 'Sadly cannot')], coerce=int, validators=[InputRequired()], widget=TableWidget(), default=1)
    submit = SubmitField('Submit')

class DetailsForm(FlaskForm):
    attendees = SelectMultipleField(coerce=int, validators=[InputRequired()], widget=TableWidget(), option_widget=CheckboxInput())
    guest = StringField(validators=[InputRequired()])
    email = EmailField(validators=[InputRequired(), Email()])
    lodging = StringField(validators=[InputRequired()])
    diet = StringField()
    songs = FieldList(StringField(), min_entries=1, max_entries=3)
    extras = SelectMultipleField(widget=TableWidget(), option_widget=CheckboxInput())
    submit = SubmitField('Submit')

class SubmitForm(FlaskForm):
    submit = SubmitField('Submit')


bandb/rsvp/__init__.py

from flask import Blueprint

rsvp = Blueprint('rsvp', __name__, template_folder='templates')

from . import views

bandb/rsvp/views.py

from flask import redirect, session, render_template, request, flash
from flask.helpers import url_for

from . import rsvp
from .sheets import RsvpSheet
from .forms import VerifyForm, ResponseForm, DetailsForm, SubmitForm

def get_rsvp_sheet():
    s = RsvpSheet()
    if (s.has_error()):
        raise s.get_error()
    return s

@rsvp.route('/')
def index():
    return render_template('rsvp/pages/landing.html', showhero=True)

@rsvp.route('/main')
def main():
    if ('rsvp_id' not in session):
        flash('Welcome, please verify your invitation')
        return redirect(url_for('.verify'))
    sh = get_rsvp_sheet()
    if (not sh.has_rsvp(session['rsvp_id'])):
        flash('Welcome, please RSVP')
        return redirect(url_for('.response'))
    data = sh.get_rsvp(session['rsvp_id'])
    if (data['people']):
        session['attending'] = True
        session['attendees'] = data['people']
    else:
        session['attending'] = False
    flash('Welcome back, your RSVP is shown')
    return redirect(url_for('.summary'))

@rsvp.route('/verify', methods=['GET', 'POST'])
def verify():
    form = VerifyForm()
    errors = None
    if (form.validate_on_submit()):
        print(form.data)
        data = get_rsvp_sheet().get_invitee(last_name=form.last_name.data, invite_code=form.invite_code.data.upper())
        if (data is not None):
            print(data)
            session['rsvp_id'] = data['id']
            session['people'] = (data['people'] if isinstance(data['people'], list) else [data['people']])
            session['addressee'] = data['addressee']
            session['guest'] = data['guest']
            session['rehearsal'] = data['rehearsal']
            print(session)
            flash('Thanks for verifying your invitation')
            return redirect(url_for('.main'))
        else:
            flash('Invitation not found, please double check your entries')
    elif (form.errors):
        if ('last_name' in form.errors):
            flash('Verify you\'ve entered your last name correctly')
        if ('invite_code' in form.errors):
            flash('Verify you\'ve entered your 4 digit invite code correctly')
        if ('csrf_token' in form.errors):
            flash('Something went wrong, please try again')
        errors = form.errors
    return render_template('rsvp/pages/verify.html', form=form, errors=errors)

@rsvp.route('/clear')
def clear():
    session.clear()
    flash('Session cleared')
    return redirect(url_for('.main'))

@rsvp.route('/reset')
def reset():
    data = get_rsvp_sheet().get_invitee(rsvp_id=session['rsvp_id'])
    session.clear()
    if (data is not None):
        print(data)
        session['rsvp_id'] = data['id']
        session['people'] = (data['people'] if isinstance(data['people'], list) else [data['people']])
        session['addressee'] = data['addressee']
        session['guest'] = data['guest']
        session['rehearsal'] = data['rehearsal']
        print(session)
    flash('Session reset')
    return redirect(url_for('.main'))

@rsvp.route('/response', methods=['GET', 'POST'])
def response():
    if ('rsvp_id' not in session):
        flash('Please verify your invitation first')
        return redirect(url_for('.main'))
    form = ResponseForm()
    errors = None
    if (form.validate_on_submit()):
        print(form.data)
        session['attending'] = bool(form.attending.data)
        if (not session['attending']):
            flash('We\'re sorry you can\'t make it!  Please confirm your RSVP.')
            return redirect(url_for('.review'))
        flash('We\'re thrilled you can make it!  Please provide some more details.')
        return redirect(url_for('.details'))
    elif (form.errors):
        if ('attending' in form.errors):
            flash('Verify you\'ve selected a response')
        if ('csrf_token' in form.errors):
            flash('Something went wrong, please try again')
        flash(form.errors)
        errors = form.errors
    return render_template('rsvp/pages/response.html', form=form, errors=errors)

@rsvp.route('/details', methods=['GET', 'POST'])
def details():
    if (not 'rsvp_id' in session):
        flash('Please verify your invitation first')
        return redirect(url_for('.main'))
    form = DetailsForm()
    errors = None
    form.attendees.choices = [(idx, name) for idx, name in enumerate(session['people'])]
    if (session['guest']):
        form.attendees.choices.append((99, 'Guest'))
        form.guest.default = 'Guest of ' + session['addressee']
        if (not form.guest.data):
            form.guest.data = form.guest.default
    else:
        del form.guest
    form.extras.choices = [('nats', 'Nationals vs Rockies - Thurs, 7:05pm'), ('5k', 'Crystal City 5k - Fri, 6:30pm')]
    if (session['rehearsal']):
        form.extras.choices.append(('rehearsal', 'Rehearsal Dinner - Fri, 7:30pm'))
    form.extras.choices.append(('brunch', 'Brunch - Sun, morning'))
    if (form.validate_on_submit()):
        print(form.data)
        session['attendees'] = [session['people'][idx] for idx in form.attendees.data if idx < 99]
        if (session['guest'] and 99 in form.attendees.data):
            session['bringing_guest'] = True
            session['attendees'].append(form.guest.data)
        if (form.email.data):
            session['email'] = form.email.data.strip()
        if (form.lodging.data):
            session['lodging'] = form.lodging.data.strip()
        if (form.diet.data):
            session['diet'] = form.diet.data.strip()
        if (form.songs.data):
            session['songs'] = [song.strip() for song in form.songs.data if song.strip()]
        if (form.extras.data):
            session['extras'] = [extra for extra in form.extras.data if extra]
        flash('Thanks for providing us some info!  Please confirm your RSVP')
        return redirect(url_for('.review'))
    elif (form.errors):
        for fld in form.errors:
            if ('attendees' in form.errors):
                flash('Verify you\'ve selected who\'s attending')
            if ('guest' in form.errors):
                flash('Verify you\'ve entered your guest\'s name')
            if ('email' in form.errors):
                flash('Verify you\'ve entered a valid email address')
            if ('lodging' in form.errors):
                flash('Verify you\'ve entered your lodging information')
            if ('diet' in form.errors):
                flash('Verify you\'re dietary information')
            if ('songs' in form.errors):
                flash('Verify you\'re song entries')
            if ('extras' in form.errors):
                flash('Verify you\'re selelction of other activities')
            if ('csrf_token' in form.errors):
                flash('Something went wrong, please try again')
        errors = form.errors
    return render_template('rsvp/pages/details.html', form=form, errors=errors)

@rsvp.route('/review', methods=['GET', 'POST'])
def review():
    if ('rsvp_id' not in session):
        flash('Please verify your invitation first')
        return redirect(url_for('.main'))
    if ('attending' not in session):
        flash('Please complete your RSVP first')
        return redirect(url_for('.main'))
    form = SubmitForm()
    if (form.validate_on_submit()):
        res = get_rsvp_sheet().save_rsvp(session['rsvp_id'],
                                         session['addressee'],
                                         session['attendees'] if session['attending'] else None,
                                         True if 'bringing_guest' in session and session['bringing_guest'] else False,
                                         session['email'] if 'email' in session else None,
                                         session['lodging'] if 'lodging' in session else None,
                                         session['songs'] if 'songs' in session else None,
                                         session['diet'] if 'diet' in session else None,
                                         session['extras'] if 'extras' in session else None)
        flash('RSVP Saved')
        return redirect(url_for('.summary'))
    elif (form.errors):
        if ('csrf_token' in form.errors):
            flash('Something went wrong, please try again')
    data = {key: session[key] for key in ['addressee', 'attending', 'attendees', 'email', 'lodging', 'diet', 'songs', 'extras'] if key in session}
    return render_template('rsvp/pages/review.html', data=data, form=form)

@rsvp.route('/summary')
def summary():
    if ('rsvp_id' not in session):
        flash('Please verify your invitation first')
        return redirect(url_for('.main'))
    if ('attending' not in session):
        flash('Please complete your RSVP first')
        return redirect(url_for('.main'))
    data = {key: session[key] for key in ['addressee', 'attending', 'attendees'] if key in session}
    return render_template('rsvp/pages/summary.html', data=data)

bandb/templates/rsvp/pages/details.html
{% extends "rsvp/rsvp_base.html" %}

{% block js %}
{{ super() }}
<script type="text/javascript">
$(document).ready(function() {
	var nsongs = {{ form.songs|length }};
	if (nsongs >= 3) {
		$('#songs-add').remove();
		return;
	}
	$('#songs-add-link').click(function() {
		if (nsongs >= 3) {
			$('#songs-add').hide(200)
			setTimeout(function(){$('#songs-add').remove();}, 300);
			return;
		}
		var sp = $('.song-input').last().clone();
		var inp = $('input', sp);
		inp.attr('id', inp.attr('id').slice(0,-1) + (Number(inp.attr('id').slice(-1)) + 1));
		inp.attr('name', inp.attr('name').slice(0,-1) + (Number(inp.attr('name').slice(-1)) + 1));
		inp.val('');
		sp.hide()
		$('#songs').append(sp);
		sp.show(200);
		nsongs ++;
		if (nsongs >= 3) {
			$('#songs-add').hide(200)
			setTimeout(function(){$('#songs-add').remove();}, 300);
		}
	});
	$('#guest').hide();
	$(':checkbox[value=99]').change(function() {
		if (this.checked)
			$('#guest').show(200);
		else
			$('#guest').hide(200);
	});
});
</script>
{% endblock js %}

{% block rsvp_content %}
<form action="{{ url_for('rsvp.details') }}" method="post">
	{{ form.hidden_tag() }}
    <div class="row">
		<h2 class="col">
			Please provide a few details!
		</h2>
	</div>
	<div class="row">
		<h4 class="col">
			Who will be there?
		</h4>
	</div>
	<div class="row checkboxes">
		<div class="col">
			{% for subfield in form.attendees %}
				<div class="row">
					<div class="col">
						{{ subfield() }}
						<label for="{{ subfield.id }}">{{ subfield.label.text }}</label>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
	{% if 'guest' in form %}
		<div class="row" id="guest">
			<div class="col input-field">
				{% if errors.guest %}
					{{ form.guest(class_="validate invalid", required="required") }}
				{% else %}
					{{ form.guest(class_="validate", required="required") }}
				{% endif %}
				<label for="{{ form.guest.id }}">Guest Name</label>
			</div>
		</div>
	{% endif %}
	<div class="row">
		<h4 class="col">
			How can we contact you?
		</h4>
	</div>
	<div class="row">
		<div class="col input-field">
			{% if errors.email %}
				{{ form.email(class_="validate invalid", required="required") }}
			{% else %}
				{{ form.email(class_="validate", required="required") }}
			{% endif %}
			<label for="{{ form.email.id }}" data-error="Please enter a valid email">Email</label>
		</div>
	</div>
	<div class="row">
		<h4 class="col full">
			Where will you be staying?
		</h4>
		<div class="col full">
			<a href="{{ url_for('main.hotel') }}" target="_blank">Click here</a> to book a room in our hotel block at the Capitol Hill Hotel
		</div>
	</div>
	<div class="row">
		<div class="col input-field">
			{% if errors.lodging %}
				{{ form.lodging(class_="validate invalid", required="required") }}
			{% else %}
				{{ form.lodging(class_="validate", required="required") }}
			{% endif %}
			<label for="{{ form.lodging.id }}">Lodging</label>
		</div>
	</div>
	<div class="row">
		<h4 class="col">
			Do you have any allergies or food restrictions?
		</h4>
	</div>
	<div class="row">
		<div class="col input-field">
			{% if errors.diet %}
				{{ form.diet(class_="validate invalid") }}
			{% else %}
				{{ form.diet(class_="validate") }}
			{% endif %}
			<label for="{{ form.diet.id }}">Dietary Requirements</label>
		</div>
	</div>
	<div class="row">
		<h4 class="col">
			We want everyone to have a good time, so give us a few songs that you promise you'll dance to if we play them!
		</h4>
	</div>
	<div class="row">
		<div class="col" id="songs">
			{% for subfield in form.songs %}
				<div class="row song-input">
					<div class="col input-field">
						{{ subfield() }}
						<label for="{{ subfield.id }}">Song Name and Artist</label>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
	<div class="row" id="songs-add">
		<div class="col">
			<a href='#' id="songs-add-link">Add a Song</a>
		</div>
	</div>
	<div class="row">
		<h4 class="col">
			Are you interested in joining us for some of the other fun activities we're planning?
		</h4>
	</div>
	<div class="row checkboxes">
		<div class="col">
			{% for subfield in form.extras %}
				<div class="row">
					<div class="col">
						{{ subfield() }}
						<label for="{{ subfield.id }}">{{ subfield.label.text }}</label>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
    <div class="row">
		<div class="col input-field">
			<button class="btn" type="submit" name="action">Submit</button>
		</div>
	</div>
</form>
{% endblock rsvp_content%}

bandb/templates/rsvp/pages/landing.html
{% extends "rsvp/rsvp_base.html" %}

{% block rsvp_content %}
<div class="row">
    <h2 class="col">
        <a href="{{ url_for('rsvp.main') }}">
            Click here to let us know if you can join us!
        </a>
    </h2>
</div>
<div class="row">
    <div class="col">
        And by the way, hold your thumb over the stamp on your
        invitation to warm it up and see what's blocking the sun!
    </div>
</div>
{% endblock %}

bandb/templates/rsvp/pages/response.html
{% extends "rsvp/rsvp_base.html" %}

{% block rsvp_content %}
<form action="{{ url_for('rsvp.response') }}" method="post">
    {{ form.hidden_tag() }}
    <div class="row">
        <h2 class="col">
            Will you be joining us?
        </h2>
    </div>
    <div class="row">
        {% for subfield in form.attending %}
            <div class="col xs-full s-auto">
                {{ subfield(class_="with-gap") }}
                <label for="{{ subfield.id }}">{{ subfield.label.text }}</label>
            </div>
        {% endfor %}
        <div class="col input-field">
            <button class="btn" type="submit" name="action">Submit</button>
        </div>
    </div>
</form>
{% endblock rsvp_content%}

bandb/templates/rsvp/pages/review.html
{% extends "rsvp/rsvp_base.html" %}

{% block rsvp_content %}
<div class="row">
    <h2 class="col">
        Please confirm that everything looks right!
    </h2>
</div>
<div class="row">
    <h4 class="col">
        You have indicated that you will
        {% if not data.attending %}
            not
        {% endif %}
        be joining us
    </h4>
</div>
{% if data.attending %}
    <div class="row">
        <div class="col">
            People attending:<br>
            {% for attendee in data.attendees %}
                {{ attendee }}<br>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Contact Email: {{ data.email }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Lodging: {{ data.lodging }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            Dietary Restrictions:
            {% if data.diet %}
                {{ data.diet }}
            {% else %}
                None
            {% endif %}
        </div>
    </div>
    {% if data.songs %}
        <div class="row">
            <div class="col">
                Song suggestions:<br>
                {% for song in data.songs %}
                    {{ song }}<br>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endif %}
<form action="{{ url_for('rsvp.review') }}" method="post">
    {{ form.hidden_tag() }}
    <div class="row">
        <div class="col input-field">
            <button class="btn" type="submit" name="action">Looks good</button>
        </div>
    </div>
</form>
<div class="row">
        <h4 class="col">
            If something doesn't look right, just hit the back button on your browser and fix it!
        </h4>
    </div>
{% endblock rsvp_content%}

bandb/templates/rsvp/pages/summary.html
{% extends "rsvp/rsvp_base.html" %}

{% block rsvp_content %}
<div class="row">
    <h2 class="col">
        Thanks for getting back to us,
        {% if data.attending %}
            we'll see you there!
        {% else %}
            we'll miss you!
        {% endif %}
    </h2>
</div>
<div class="row">
    <h2 class="col">
        <a href="/">Back Home</a>
    </h2>
</div>
{% endblock rsvp_content%}

bandb/templates/rsvp/pages/verify.html
{% extends "rsvp/rsvp_base.html" %}

{% block rsvp_content %}
<form action="{{ url_for('rsvp.verify') }}" method="post">
    {{ form.hidden_tag() }}
    <div class="row">
        <h2 class="col">
            Please verify your invitation using the 4 digit code on your RSVP card.
        </h2>
    </div>
    <div class="row">
        <div class="col input-field">
            {% if errors.last_name %}
                {{ form.last_name(class_="validate invalid", required="required") }}
            {% else %}
                {{ form.last_name(class_="validate", required="required") }}
            {% endif %}
            <label for="{{ form.last_name.id }}">Last Name</label>
        </div>
    </div>
    <div class="row">
        <div class="col input-field">
            {% if errors.invite_code %}
                {{ form.invite_code(class_="validate invalid", required="required") }}
            {% else %}
                {{ form.invite_code(class_="validate", required="required") }}
            {% endif %}
            <label for="{{ form.invite_code.id }}">Invite Code</label>
        </div>
    </div>
    <div class="row">
        <div class="col input-field">
            <button class="btn" type="submit" name="action">Submit</button>
        </div>
    </div>
</form>
{% endblock rsvp_content %}